import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import initTranslations from '../i18n'
import TranslationsProvider from '@/components/TranslationsProvider'
import ClientProviders from '@/components/ClientProviders'

export const metadata: Metadata = {
  title: 'Audiophile',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode
  params: { locale: string }
}>) {
  const { resources } = await initTranslations(locale, ['default', 'common'])

  return (
    <html lang={locale}>
      <body>
        <ClientProviders>
          <TranslationsProvider
            resources={resources}
            locale={locale}
            namespaces={['default', 'common']}
          >
            <Header />
            {children}
            <Footer />
          </TranslationsProvider>
        </ClientProviders>
      </body>
    </html>
  )
}
