import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import initTranslations from '../i18n'
import TranslationsProvider from '@/components/TranslationsProvider'
import { createClient } from '@/utils/supabase/server'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode
  params: { locale: string }
}>) {
  const { resources } = await initTranslations(locale, ['default', 'common'])
  const supabase = await createClient()
  const { data } = await supabase.auth.getUser()

  return (
    <html lang={locale}>
      <body>
        <TranslationsProvider
          resources={resources}
          locale={locale}
          namespaces={['default', 'common']}
        >
          <Header user={data.user} />
          {children}
          <Footer />
        </TranslationsProvider>
      </body>
    </html>
  )
}
